export enum Permission {
    ADMIN_READ = "ADMIN_READ", 
    ADMIN_UPDATE = "ADMIN_UPDATE",
    ADMIN_CREATE = "ADMIN_CREATE", 
    ADMIN_DELETE = "ADMIN_DELETE", 
    EMPLOYEE_READ = "EMPLOYEE_READ",
    EMPLOYEE_UPDATE = "EMPLOYEE_UPDATE", 
    EMPLOYEE_CREATE = "EMPLOYEE_CREATE",
    EMPLOYEE_DELETE = "EMPLOYEE_DELETE" 
}